### ISSUE TITLE
Bug (again) in edition/add

### ISSUE THREAD

**Issue by PietroDelcorno** [ErwinKomen/RU-lenten#71]
![Problem](https://user-images.githubusercontent.com/65396747/94343034-9fc91200-0015-11eb-9e49-7404661392a0.PNG)

Hi Erwin,

Finally, after a few weeks, I went back to work on the database - and I imediately stumbled in a bug. I added a new author (no problem), I added a new collection (no problem), yet when I tryed to add a new edition, I could introduce the data but at the moment of saveing it gave me the usual message of error (see image).

**Comment by ErwinKomen** [comment]
Thanks for the good report. This meant fixing it was trivial.
There was a small bug in `models.py`, `Edition` method `get_year()`
Fixed it, checked it, works.

**Comment by PietroDelcorno** [comment]
No, the issue is still not solved. If I try to add an edition, there is the same problem, Now with this message

![image](https://user-images.githubusercontent.com/65396747/95554627-c7a27780-0a10-11eb-8e39-8308286a4885.png)

**Comment by PietroDelcorno** [comment]
This was the data that I was trying to do (in case you need to check)
![image](https://user-images.githubusercontent.com/65396747/95555538-3cc27c80-0a12-11eb-879b-bc6d79af1538.png)

**Comment by ErwinKomen** [comment]
The problem is here as well as in issue #72, what happens when an edition is removed?
When that happens, and this edition is the 'firstedi' in one (or more) of the SermonCollection objects, the firstedi should be adapted.

**Comment by ErwinKomen** [comment]
Seems to be solved now
